### ISSUE TITLE
Authorization Request Errors

### ISSUE THREAD

**Issue by s2t2** [rossetti-gov/my-identity-sp-express#1]
So far when trying to connect to local identity-idp, running into authorization request errors:

```js
Error in OIDC setup { RequestError: connect ECONNREFUSED 127.0.0.1:3000
    at ClientRequest.req.once.err (/Users/MYUSERNAME/projects/18f/my-identity-sp/node_modules/openid-client/node_modules/got/index.js:219:22)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'RequestError',
  code: 'ECONNREFUSED',
  host: 'localhost:3000',
  hostname: 'localhost',
  method: 'GET',
  path: '/.well-known/openid-configuration',
  protocol: 'http:',
  url: 'http://localhost:3000/.well-known/openid-configuration' }
```

Should try registering this client by:
  + choosing some [client attributes](https://developers.login.gov/register/#openid-connect) like an id of `urn:gov:gsa:openidconnect:sp:mjr-express-dev`, 
  + [generating new test keys](https://developers.login.gov/certs/) (OR IS THIS ONLY RELEVANT FOR SAML?), and
  + emailing them to partners@login.gov and/or slacking the integration channel

But first try using PEM instead of JWK?

**Comment by s2t2** [comment]
Closing this issue in favor of https://github.com/18F/identity-oidc-expressjs/issues/1
